{"text": "Self Supervised Learning is an interesting research area where the goal is to learn rich representations from unlabeled data without any human annotation.", "meta": {"title": "Knowledge Transfer in Self Supervised Learning"}}
{"text": "Hugging Face recently released ", "meta": {"title": "Text Data Augmentation with MarianMT"}}
{"text": " is a free web application for visualizing high-dimensional data. It has built-in demos for visualizing word embeddings in NLP and image embeddings for MNIST in Computer Vision.", "meta": {"title": "Interactive Analysis of Sentence Embeddings"}}
{"text": "It\u2019s a common task in NLP to either check a text against a pattern or extract parts from the text that matches a certain pattern. A regular expression or \u201cregex\u201d is a powerful tool to achieve this.", "meta": {"title": "A Visual Guide to Regular Expression"}}
{"text": "I recently discovered a way to set up VSCode on Google Colab and use it as an editor to write code and run experiments on the Colab VM.", "meta": {"title": "VSCode on Google Colab"}}
{"text": "While Flask has become the de-facto choice for API development in Machine Learning projects, there is a new framework called FastAPI that has been getting a lot of community traction.", "meta": {"title": "FastAPI for Flask Users"}}
{"text": "Keyword Extraction is one of the simplest ways to leverage text mining for providing business value. It can automatically identify the most representative terms in the document.", "meta": {"title": "Unsupervised Keyphrase Extraction"}}
{"text": "When developing an NLP model, it\u2019s a standard practice to test how well a model generalizes to unseen examples by evaluating it on a held-out dataset. Suppose we reach our target performance metric of 95% on a held-out dataset and thus deploy the model to production based on this single metric.", "meta": {"title": "Behavioral Testing of NLP models with CheckList"}}
{"text": "Most software products we encounter today have some form of search functionality integrated into them. We search for content on Google, videos on YouTube, products on Amazon, messages on Slack, emails on Gmail, people on Facebook, and so on.", "meta": {"title": "Evaluation Metrics For Information Retrieval"}}
{"text": "Semi-supervised learning methods for Computer Vision have been advancing quickly in the past few years. Current state-of-the-art methods are simplifying prior work in terms of architecture and loss function or introducing hybrid methods by blending different formulations.", "meta": {"title": "Semi-Supervised Learning in Computer Vision"}}
{"text": "Word Embeddings are one of the most interesting aspects of the Natural Language Processing field. When I first came across them, it was intriguing to see a simple recipe of unsupervised training on a bunch of text yield representations that show signs of syntactic and semantic understanding.", "meta": {"title": "A Visual Guide to FastText Word Embeddings"}}
{"text": "I recently completed the UC Berkeley\u2019s ", "meta": {"title": "Exploring Knowledge Captured in Probability of Strings"}}
{"text": "With transformer models such as BERT and friends taking the NLP research community by storm, it might be tempting to just throw the latest and greatest model at a problem and declare it done. However, in industry, we have compute and memory limitations to consider and might not even have a dedicated GPU for inference.", "meta": {"title": "Universal Sentence Encoder Visually Explained"}}
{"text": "Colab is one of the best products to come from Google. It has made GPUs freely accessible to learners and practitioners like me who otherwise wouldn\u2019t be able to afford a high-end GPU.", "meta": {"title": "Google Colab Tips for Power Users"}}
{"text": "In my ", "meta": {"title": "Zero-shot Text Classification With Generative Language Models"}}
{"text": "While Computer Vision is making ", "meta": {"title": "Self Supervised Representation Learning in NLP"}}
{"text": "The recent release of GPT-3 got me interested in the state of zero-shot learning and few-shot learning in NLP. While most of the zero-shot learning research is concentrated in Computer Vision, there has been some interesting work in the NLP domain as well.", "meta": {"title": "Zero Shot Learning for Text Classification"}}
{"text": "I recently came across an interesting thread on Twitter discussing a hypothetical scenario where research papers are published on GitHub and subsequent papers are diffs over the original paper. Information overload has been a real problem in ML with so many new papers coming every month.", "meta": {"title": "A Commit History of BERT and its Forks"}}
{"text": "Keras provides a powerful abstraction for recurrent layers such as RNN, GRU, and LSTM for Natural Language Processing. When I first started learning about them from the documentation, I couldn\u2019t clearly understand how to prepare input data shape, how various attributes of the layers affect the outputs, and how to compose these layers with the provided abstraction.", "meta": {"title": "A Visual Guide to Recurrent Layers in Keras"}}
{"text": "Unlike Computer Vision where using image data augmentation is standard practice, augmentation of text data in NLP is pretty rare. Trivial operations for images such as rotating an image a few degrees or converting it into grayscale doesn\u2019t change its semantics. This presence of semantically invariant transformation made augmentation an essential toolkit in Computer Vision research.", "meta": {"title": "A Visual Survey of Data Augmentation in NLP"}}
{"text": "The end of 2019 saw a huge surge in the number of self-supervised learning research papers using contrastive learning. In December 2019, ", "meta": {"title": "The Illustrated PIRL: Pretext-Invariant Representation Learning"}}
{"text": "Many self-supervised methods use ", "meta": {"title": "A Visual Exploration of DeepCluster"}}
{"text": "Deep Learning has shown very promising results in the area of Computer Vision. But when applying it to practical domains such as medical imaging, lack of labeled data is a major hurdle.", "meta": {"title": "The Illustrated FixMatch for Semi-Supervised Learning"}}
{"text": "PyTorch has emerged as one of the go-to deep learning frameworks in recent years. This popularity can be attributed to its easy to use API and it being more \u201cpythonic\u201d.", "meta": {"title": "The Python Magic Behind PyTorch"}}
{"text": "In the past year, several methods for self-supervised learning of image representations have been proposed. A recent trend in the methods is using Contrastive Learning (", "meta": {"title": "A Visual Guide to Self-Labelling Images"}}
{"text": "When working on Natural Language Processing applications such as Text Classification, collecting enough labeled examples for each category manually can be difficult. In this article, I will go over an interesting technique to augment your existing text data automatically called back translation.", "meta": {"title": "Back Translation for Text Augmentation with Google Sheets"}}
{"text": "Consider a sentence given below. As humans, when we encounter the word \u201c", "meta": {"title": "Visual Paper Summary: ALBERT (A Lite BERT)"}}
{"text": "Tensorflow 2.0 introduced Keras as the default high-level API to build models. Combined with pretrained models from Tensorflow Hub, it provides a dead-simple way for transfer learning in NLP to create good models out of the box.", "meta": {"title": "Transfer Learning in NLP with Tensorflow Hub and Keras"}}
{"text": "In recent years, ", "meta": {"title": "The Illustrated SimCLR Framework"}}
{"text": "I first got introduced to self-supervised learning in a ", "meta": {"title": "The Illustrated Self-Supervised Learning"}}
{"text": "I recently worked on a Django web application which was deployed on a Linux Server with SSH access. Deployments\nwere done manually and the CI/CD pipeline was still in planning.", "meta": {"title": "How to Automate Manual Steps after SSH"}}
{"text": "Text Language Identification is the process of predicting the language of a given piece of text. You might have encountered it when Chrome shows a popup to translate a webpage when it detects that the content is not in English. Behind the scenes, Chrome is using a model to predict the language of text used on a webpage.", "meta": {"title": "Identify the Language of Text using Python"}}
{"text": "When working with Machine Learning projects, you will come across a wide variety of equations that you need to implement in code. Mathematical notations capture a concept so eloquently but unfamiliarity with them makes them obscure.", "meta": {"title": "Math Symbols Explained with Python"}}
{"text": "If you are migrating to Django from another MVC framework, chances are you already know SQL.", "meta": {"title": "Django ORM if you already know SQL"}}
{"text": "In this article, I will go over the most frequent tasks related to file paths and show how you can refactor the old approach of using ", "meta": {"title": "Migrating from OS.PATH to PATHLIB Module in Python"}}
{"text": "In Windows, we can use Alt+F4 keyboard shortcut to shutdown. But Linux doesn\u2019t have such feature out of the box. After switching to Ubuntu, I struggled trying to make a keyboard shortcut for shutting down the computer.", "meta": {"title": "Shutdown Ubuntu With A Keyboard Shortcut"}}
